name: "Telegram PR Notifications"

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the develop branch
on:
  pull_request:
    branches: [develop]
  # pull_request_review:
  #   types: [submitted]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Send a message to telegram that there is a new pull request
      - name: "Send Message to Telegram Pull Request Channel"
        run: curl
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID_PR }}
          -d text="<b>[PIKOBAR]</b> <a href='${{ github.event.pull_request.html_url }}'><b>${{ github.event.pull_request.title }} ${{ github.event.pull_request.number }}</b></a> by ${{ github.event.pull_request.user.login }} %0A%0A${{ github.event.pull_request.html_url }}"
          -d parse_mode="html"
          -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage

